--Chapter4 INTEGER
--SMALLINT 2바이트
--INTEGER  4바이트
--BIGINT   8바이트
--각 데이터 타입의 사이즈를 감안하여 테이블 생성 시 활용해야 한다.

--SMALLINT
CREATE TABLE BOOKS (
BOOK_ID SERIAL PRIMARY KEY
, TITLE VARCHAR (255) NOT NULL
, PAGES SMALLINT NOT NULL CHECK (PAGES > 0)
);
--책의 페이즈는 32,767을 넘지 않는다

CREATE TABLE CITIES (
CITY_ID SERIAL PRIMARY KEY
, CITY_NAME VARCHAR (255) NOT NULL
, POPULATION INT NOT NULL CHECK (POPULATION >= 0)
);
--도시의 인구는 절대로 2,147,483,647명을 넘지않는다
