--Chapter5 SERIAL
--순차적으로 1,2,3,4,5 .... 
CREATE TABLE TABLE_NAME
(
ID SERIAL
);
INSERT INTO TABLE_NAME
VALUES(DEFAULT);
COMMIT;

select * from TABLE_NAME;
--------------------------------------------------------------------
CREATE SEQUENCE TABLE_NAME_ID_SEQ;
CREATE TABLE TABLE_NAME 
(
ID INTEGER NOT NULL DEFAULT
NEXTVAL('TABLE_NAME_ID_SEQ')
);
ALTER SEQUENCE TABLE_NAME_ID_SEQ OWNED BY TABLE_NAME.ID;
INSERT INTO TABLE_NAME VALUES(DEFAULT);
COMMIT;
SELECT * FROM TABLE_NAME;
--------------------------------------------------------------------
--SERIAL데이터 타입은 PK에 자주 사용된다.
CREATE TABLE FRUITS(
ID SERIAL PRIMARY KEY
, NAME VARCHAR NOT NULL
);
INSERT INTO FRUITS(NAME) VALUES('orange');
INSERT INTO FRUITS(ID,NAME) VALUES(DEFAULT,'apple');

select * from FRUITS;
