--Chapter 17 LAG,LEAD함수
--LAG함수 - 이전 행의 값을 찾는다.
SELECT 
	A.PRODUCT_NAME,
	A.PRICE,
	B.GROUP_NAME,
	LAG(A.PRICE, 1) OVER (PARTITION BY B.GROUP_NAME ORDER BY A.PRICE ) AS PREV_PRICE,
	A.PRICE - LAG(A.PRICE, 1) OVER (PARTITION BY B.GROUP_NAME ORDER BY A.PRICE ) AS CUR_PREV_DIFF
FROM 
	PRODUCT A
INNER JOIN	PRODUCT_GROUP B
ON A.GROUP_ID = B.GROUP_ID;
--------------------------------------------------------------------------
--LEAD 함수 - 다음 행의 값을 찾는다
SELECT 
	A.PRODUCT_NAME,
	A.PRICE,
	B.GROUP_NAME,
	LEAD(A.PRICE, 1) OVER (PARTITION BY B.GROUP_NAME ORDER BY A.PRICE ) AS NEXT_PRICE,
	A.PRICE - LEAD(A.PRICE, 1) OVER (PARTITION BY B.GROUP_NAME ORDER BY A.PRICE ) AS CUR_NEXT_DIFF
FROM 
	PRODUCT A
INNER JOIN	PRODUCT_GROUP B
ON A.GROUP_ID = B.GROUP_ID;
